In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [2]:
import numpy as np


In [6]:
import matplotlib.pyplot as plt

In [7]:
from sklearn.datasets import load_digits
digits = load_digits()

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [9]:
X_train

array([[ 0.,  0., 15., ...,  0.,  0.,  0.],
       [ 0.,  0., 12., ...,  9.,  0.,  0.],
       [ 0.,  0.,  6., ..., 14., 13.,  0.],
       ...,
       [ 0.,  0.,  4., ...,  8.,  0.,  0.],
       [ 0.,  0.,  3., ...,  5.,  0.,  0.],
       [ 0.,  0.,  2., ..., 16.,  7.,  0.]])

In [10]:
len(X_train)

1257

In [11]:
y_train

array([5, 3, 2, ..., 3, 0, 6])

In [12]:
len(y_train)

1257

In [13]:
X_test

array([[ 0.,  0.,  5., ..., 15.,  3.,  0.],
       [ 0.,  0.,  8., ...,  3.,  0.,  0.],
       [ 0.,  0.,  1., ...,  8.,  0.,  0.],
       ...,
       [ 0.,  0.,  2., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [14]:
len(X_test)

540

In [15]:
y_test

array([9, 8, 0, 9, 1, 3, 4, 6, 5, 2, 7, 3, 6, 3, 0, 8, 7, 0, 4, 1, 6, 7,
       1, 4, 5, 1, 8, 0, 5, 6, 1, 1, 2, 0, 8, 3, 7, 5, 5, 2, 1, 6, 5, 9,
       1, 6, 7, 0, 4, 3, 2, 6, 6, 3, 0, 3, 1, 4, 2, 2, 8, 0, 8, 7, 8, 9,
       0, 5, 7, 4, 9, 2, 3, 9, 4, 9, 5, 0, 7, 0, 2, 7, 8, 6, 7, 8, 3, 5,
       5, 9, 8, 2, 6, 5, 1, 9, 0, 6, 1, 7, 6, 9, 4, 9, 9, 7, 1, 4, 1, 8,
       7, 9, 5, 5, 3, 3, 6, 5, 4, 9, 3, 0, 2, 8, 7, 8, 0, 6, 3, 4, 1, 6,
       3, 3, 0, 3, 5, 5, 8, 7, 2, 4, 4, 1, 9, 5, 9, 2, 5, 9, 3, 0, 4, 5,
       4, 5, 9, 8, 2, 7, 0, 2, 7, 1, 4, 8, 6, 9, 7, 6, 3, 1, 4, 0, 0, 1,
       7, 8, 6, 0, 1, 9, 8, 0, 6, 4, 4, 5, 5, 6, 7, 4, 9, 7, 5, 8, 6, 3,
       6, 9, 8, 6, 2, 0, 3, 8, 3, 8, 6, 1, 6, 8, 2, 7, 8, 9, 7, 4, 3, 5,
       2, 6, 2, 5, 3, 8, 9, 9, 3, 6, 2, 6, 2, 8, 3, 8, 3, 4, 1, 5, 0, 4,
       8, 4, 7, 7, 2, 8, 4, 8, 3, 2, 8, 1, 2, 5, 1, 2, 3, 6, 0, 8, 4, 8,
       0, 1, 9, 5, 9, 3, 8, 2, 0, 3, 7, 6, 3, 1, 9, 9, 4, 8, 4, 1, 6, 3,
       6, 6, 5, 8, 2, 7, 7, 5, 8, 2, 9, 9, 9, 3, 0,

In [16]:
len(y_test)

540

In [17]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9555555555555556

In [18]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)#svm is performing better than others models. 

0.9833333333333333

In [19]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9648148148148148

In [21]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)#splitting data into 3k
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [25]:
kf.split([1,2,3,4,5,6,7,8,9])

<generator object _BaseKFold.split at 0x000002E6D3C50F48>

In [26]:
#Splitting the data into 3 stages.
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [27]:
def get_score(model,X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [28]:
get_score(LogisticRegression(),X_train, X_test, y_train, y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9555555555555556

In [29]:
get_score(SVC(),X_train, X_test, y_train, y_test)

0.9833333333333333

In [30]:
get_score(RandomForestClassifier(),X_train, X_test, y_train, y_test)

0.9666666666666667

In [38]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    
    scores_logistic.append(get_score(LogisticRegression(),X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(),X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=50),X_train, X_test, y_train, y_test))
    


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

In [39]:
scores_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [40]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [41]:
scores_rf

[0.9398998330550918, 0.9398998330550918, 0.9298831385642737]

In [42]:
from sklearn.model_selection import cross_val_score

In [43]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [44]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [45]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [46]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93333333, 0.91944444, 0.95264624, 0.9637883 , 0.93593315])

In [53]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target,cv=10)
np.average(scores1)

0.9437895716945995

In [48]:
scores1

array([0.9       , 0.96666667, 0.93333333, 0.94444444, 0.95555556,
       0.96666667, 0.96111111, 0.94972067, 0.9273743 , 0.93854749])

In [54]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=100),digits.data,digits.target,cv=10)
np.average(scores2)

0.9515704531346989

In [52]:
scores2

array([0.90555556, 0.97222222, 0.96111111, 0.95      , 0.97222222,
       0.97777778, 0.96666667, 0.96648045, 0.91620112, 0.93854749])

In [55]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=120),digits.data,digits.target,cv=10)
np.average(scores3)

0.9532588454376164